function covid19(~)

fontsize = 12;
width=.99;
init_gui;



    function load_data(~,~)
        evalin('base', 'run(''Incarcam_datele_wo_geo_cns'')')
        display('ok')
        % evalin('base','Incarcam_datele_wo_geo_cns');
    end
    function show_data(~,~)
        evalin('base', 'run(''Afisare_plot_WO_GEO_CNS'')')
        display('ok')
        
    end
    function show_data_campean(~,~)
        
        evalin('base', 'run(''C:\Users\horva\Desktop\Practica\Practica_covid19_UTCN\Coduri_matlab\Campean\Ploturi\script'')')
        display('ok')
        % evalin('base', 'run(''script'')')
        
    end
    function retea_newff(~,~)
        evalin('base', 'run(''retea_neuronala'')')
        display('ok')
        
    end
    function retea_elman(~,~)
        evalin('base', 'run(''Newelman_retea_neuronala'')')
        display('ok')
        
    end

    function retea_narxnet(~,~)
        evalin('base', 'run(''Narxnet_script'')')
        display('ok')
        
    end
    function retea_linearlayer(~,~)
        evalin('base', 'run(''LinearLayer'')')
        display('ok')
        
    end


    function  init_gui
        if isequal(get(gcf,'name'),'covid19')
            clf
        else
            set(gcf,'name','covid19','numbertitle','off')
        end
        clc
        uicontrol('style','pushbutton', ...
            'units','normal', ...
            'position',[.01 .90 width .07], ...
            'background','w', ...
            'string','Incarcare date ', ...
            'fontsize',fontsize, ...
            'fontweight','bold', ...
            'callback',@load_data);
        
        uicontrol('style','pushbutton', ...
            'units','normal', ...
            'position',[.01 .80 width .07], ...
            'background','w', ...
            'string','Afisare date script Norbert', ...
            'fontsize',fontsize, ...
            'fontweight','bold', ...
            'callback',@show_data);
        
        uicontrol('style','pushbutton', ...
            'units','normal', ...
            'position',[.01 .70 width .07], ...
            'background','w', ...
            'string','Afisare date script Campean', ...
            'fontsize',fontsize, ...
            'fontweight','bold', ...
            'callback',@show_data_campean);
        
        uicontrol('style','pushbutton', ...
            'units','normal', ...
            'position',[.01 .60 width .07], ...
            'background','w', ...
            'string','Retea Neuronala Newff , feedforward', ...
            'fontsize',fontsize, ...
            'fontweight','bold', ...
            'callback',@retea_newff);
        
        uicontrol('style','pushbutton', ...
            'units','normal', ...
            'position',[.01 .50 width .07], ...
            'background','w', ...
            'string','Retea ADALINE Elman ', ...
            'fontsize',fontsize, ...
            'fontweight','bold', ...
            'callback',@retea_elman);
        
        uicontrol('style','pushbutton', ...
            'units','normal', ...
            'position',[.01 .40 width .07], ...
            'background','w', ...
            'string','Retea ADALINE Narxnet', ...
            'fontsize',fontsize, ...
            'fontweight','bold', ...
            'callback',@retea_narxnet);
        
        uicontrol('style','pushbutton', ...
            'units','normal', ...
            'position',[.01 .30 width .07], ...
            'background','w', ...
            'string','Retea ADALINE LinearLayer', ...
            'fontsize',fontsize, ...
            'fontweight','bold', ...
            'callback',@retea_linearlayer);
        
    end
end
