function covid19(~)

fontsize = 12;
fontname = get(groot,'fixedwidthfontname');  % fixed width
width=.20;
init_gui;



    function load_data(~,~)
        evalin('base', 'run(''Incarcam_datele_wo_geo_cns'')')
       % evalin('base','Incarcam_datele_wo_geo_cns');
    end
    function show_data(~,~)
        evalin('base', 'run(''Afisare_plot_WO_GEO_CNS'')')
        
    end
    function retea_newff(~,~)
        evalin('base', 'run(''retea_neuronala'')')
        
    end
    function retea_elman(~,~)
        evalin('base', 'run(''Newelman_retea_neuronala'')')
        
    end

    function  init_gui
        if isequal(get(gcf,'name'),'covid19-1')
            clf
        else
            set(gcf,'name','covid19-1','numbertitle','off')
        end
        uicontrol('style','pushbutton', ...
            'units','normal', ...
            'position',[.01 .90 width .07], ...
            'background','w', ...
            'string','load_data', ...
            'fontsize',fontsize, ...
            'fontweight','bold', ...
            'callback',@load_data);
        uicontrol('style','pushbutton', ...
            'units','normal', ...
            'position',[.01 .80 width .07], ...
            'background','w', ...
            'string','Afisare date', ...
            'fontsize',fontsize, ...
            'fontweight','bold', ...
            'callback',@show_data);
        uicontrol('style','pushbutton', ...
            'units','normal', ...
            'position',[.01 .70 width .07], ...
            'background','w', ...
            'string','Retea Newff', ...
            'fontsize',fontsize, ...
            'fontweight','bold', ...
            'callback',@retea_newff);
        uicontrol('style','pushbutton', ...
            'units','normal', ...
            'position',[.01 .60 width .07], ...
            'background','w', ...
            'string','Retea Elman', ...
            'fontsize',fontsize, ...
            'fontweight','bold', ...
            'callback',@retea_elman);
        help_callback = @(~,~) run('Incarcam_datele_wo_geo_cns');

        
        
        
        
    end






end
