function covid19(~)

fontsize = 12;
fontname = get(groot,'fixedwidthfontname');  % fixed width
init_gui;

    function load_data(~,~)
        evalin('base','C:\Users\horva\Desktop\Practica\Practica_covid19_UTCN\Coduri_matlab\Norbert\Incarcam_datele_wo_geo_cns');
    end
    function test(~,~)
        figure ;
        
    end

    function  init_gui
        if isequal(get(gcf,'name'),'covid19-1')
            clf
        else
            set(gcf,'name','covid19-1','numbertitle','off')
        end
        uicontrol('style','pushbutton', ...
            'units','normal', ...
            'position',[.01 .90 .15 .07], ...
            'background','w', ...
            'string','load_data', ...
            'fontsize',fontsize, ...
            'fontweight','bold', ...
            'callback',@load_data);
        uicontrol('style','pushbutton', ...
            'units','normal', ...
            'position',[.01 .80 .15 .07], ...
            'background','w', ...
            'string','test', ...
            'fontsize',fontsize, ...
            'fontweight','bold', ...
            'callback',@test);
        uicontrol('style','pushbutton', ...
            'units','normal', ...
            'position',[.01 .70 .15 .07], ...
            'background','w', ...
            'string','test', ...
            'fontsize',fontsize, ...
            'fontweight','bold', ...
            'callback',@test);
        uicontrol('style','pushbutton', ...
            'units','normal', ...
            'position',[.01 .60 .15 .07], ...
            'background','w', ...
            'string','test', ...
            'fontsize',fontsize, ...
            'fontweight','bold', ...
            'callback',@test);
        help_callback = @(~,~) run('Incarcam_datele_wo_geo_cns');

        
        
        
        
    end






end
